llm -m all-MiniLM-L6-v2-f16 hello
llm -m orca-mini-3b-gguf2-q4_0 hello
llm -m gpt4all-13b-snoozy-q4_0 hello
llm -m wizardlm-13b-v1 hello
llm -m orca-2-13b hello
llm -m starcoder-q4_0 hello
llm -m replit-code-v1_5-3b-q4_0 hello
llm -m mpt-7b-chat-merges-q4_0 hello
llm -m orca-2-7b hello
llm -m rift-coder-v0-7b-q4_0 hello
llm -m em_german_mistral_v01 hello
llm -m mistral-7b-instruct-v0 hello
llm -m mistral-7b-openorca hello
llm -m gpt4all-falcon-q4_0 hello
llm -m nous-hermes-llama2-13b hello
